payment.payment_method.*:
  type: mapping
  label: 'Payment method'
  mapping:
    id:
      type: string
    label:
      type: label
    ownerId:
      type: integer
    pluginConfiguration:
      type: mapping
    pluginId:
      type: string
    status:
      type: boolean
    uuid:
      type: string

payment.payment_status.*:
  type: mapping
  label: 'Payment status'
  mapping:
    id:
      type: string
    label:
      type: label
    parentId:
      type: string
    uuid:
      type: string
