id: collect_on_delivery
label: 'Collect on delivery'
ownerId: 1
pluginConfiguration:
  message_text: 'You will be charged upon delivery. Please make sure you have enough cash available.'
  message_text_format: plain_text
  status: payment_pending
pluginId: payment_basic
status: false
