id: payment.payment_reference_field_instance_config
uuid: e54e5e54-1832-46be-9a3b-6ba355ba86de
status: true
langcode: en
name: payment_reference_field_instance_config
entity_type: payment
type: entity_reference
settings:
  target_type: field_instance_config
module: entity_reference
active: true
locked: true
cardinality: '1'
translatable: false
indexes: {  }
