payment.payment_method_configuration.*:
  type: mapping
  label: Payment method
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    ownerId:
      type: integer
      label: Owner ID
    pluginConfiguration:
      type: mapping
      label: Configuration
      mapping:
        # This is for payment method entities that use a plugin that extends
        # \Drupal\payment\Plugin\Payment\MethodConfiguration\Basic
        execute_status_id:
          label: Execute payment status
          type: string
        capture:
          label: Capture
          type: boolean
        capture_status_id:
          label: Capture payment status
          type: string
        refund:
          label: Refund
          type: boolean
        refund_status_id:
          label: Refund payment status
          type: string
        # This is for payment method entities that use a plugin that extends
        # \Drupal\payment\Plugin\Payment\MethodConfiguration\PaymentMethodConfigurationBase
        message_text:
          label: Message text
          type: text
        message_text_format:
          label: Message text format
          type: string
    pluginId:
      type: string
      label: Plugin ID
    status:
      type: boolean
      label: Status
    uuid:
      type: string
      label: UUID

payment.payment_status.*:
  type: mapping
  label: Payment status
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    parentId:
      type: string
      label: Parent ID
    uuid:
      type: string
      label: UUID
